version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "daily"
    ignored_updates:
      - match:
          dependency_name: "eslint-plugin-ember"
          # ignores any updates 9.0.0 or greater
          # since we want to explicitly upgrade this
          # dependency ourselves (it changes the nature of data tasks)
          version_requirement: "^9.0.0"
